---

- name: Create Configs Directory
  file:
    name: '{{ automation_mounted_directory }}/configs'
    state: directory

- include: home-assistant.yml
- include: ha-triggers.yml
- include: tts.yaml
