---

- include_vars: vault_plex.yml

#- name: make media mount directory
#  file:
#    name: "{{ mediaserver_mounted_directory }}"
#    state: directory
#
#- name: mount media directory
#  mount:
#    path: "{{ mediaserver_mounted_directory }}"
#    src: "{{ media_remote_directory }}"
#    fstype: "nfs"
#    opts: rw,async
#    state: present

- name: make incomplete downloads directory
  file:
    name: "{{ mediaserver_mounted_directory }}/{{ usenet_incomplete_download_directory }}"
    state: directory

- name: make complete downloads directory
  file:
    name: "{ mediaserver_mounted_directory }}/{{ usenet_complete_download_directory }}"
    state: directory

- name: make watch directory
  file:
    name: "{ mediaserver_mounted_directory }}/{{ usenet_watch_directory }}"
    state: directory

- include: sonarr.yml
- include: sabnzbd.yml
- include: radarr.yml
- include: plex.yml
