- include_vars: vault_plex.yml

- name: install mkvtoolnix
  apt: name=mkvtoolnix update_cache=yes state=latest

- name: install ffmpeg
  apt: name=ffmpeg update_cache=yes state=latest

- name: make incomplete downloads directory
  file:
    name: "{{ mediaserver_mounted_directory }}/{{ usenet_incomplete_download_directory }}"
    state: directory

- name: make complete downloads directory
  file:
    name: "{ mediaserver_mounted_directory }}/{{ usenet_complete_download_directory }}"
    state: directory

- name: make watch directory
  file:
    name: "{ mediaserver_mounted_directory }}/{{ usenet_watch_directory }}"
    state: directory

- include: sonarr.yml
- include: sabnzbd.yml
- include: radarr.yml
- include: plex.yml
