- name: 'Start plex docker container'
  docker:
    name: "{{ docker_plex_container_name }}"
    image: wernight/plex-media-server:autoupdate
    env:
      PUID: '0'
      PGID: '0'
      X_PLEX_TOKEN: '{{ plex_token }}'
      VERSION: 'latest'
    volumes:
      - '{{ mediaserver_mounted_directory }}/configs/{{ docker_plex_container_name }}:/config'
      - '{{ mediaserver_mounted_directory }}:/media'
      - '{{ mediaserver_mounted_directory }}/transcode:/transcode'
    net: host
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_opt:
      tag: "{{ docker_sabnzbd_container_name }}"
