openldap_server_pkgs:
  - slapd
  - ldap-utils
  - python-selinux
  - openssl
  - python3
  - python3-pip
  - libsasl2-dev
  - python-dev
  - libldap2-dev
  - libssl-dev

openldap_server_app_path: "/etc/ldap/"
openldap_server_user: "openldap"

