---
- include_vars: ../openldap/defaults/main.yml
- include_vars: ../openldap/vars/ssh_users.yml
- include_vars: ../openldap/vars/vault_user_passwords.yml
- include_vars: ../openldap/vars/vault.yml

- include: nfs_server.yml
  when: server | bool
- include: nfs_client.yml
