---

#The domain prefix for ldap
openldap_server_domain_name: ldap.int.teagantotally.rocks
openldap_server_ip: 10.0.10.126

#The self signed ssl parameters
openldap_server_country: US
openldap_server_state: colorado
openldap_server_location: denver
openldap_server_organization: Home

openldap_server_enable_ssl: false

#The ldif file
openldap_server_ldif: domain.ldif

openldap_server_dc: "dc={{ openldap_server_domain_name.split('.')[0] }},dc={{ openldap_server_domain_name.split('.')[1] }},dc={{ openldap_server_domain_name.split('.')[2] }},dc={{ openldap_server_domain_name.split('.')[3] }}"
openldap_server_bind_dn: "cn=Manager,{{ openldap_server_dc }}"
